### ISSUE TITLE
The minified script which is being built using npm run release is not working

### ISSUE THREAD

**Issue by chaithanyabi** [kensnyder/quill-image-resize-module#2]
The minified script which is being built using npm run release is not working. It is throwing some console errors

**Comment by gbenson-wikia** [comment]
There's a reasonable chance that this will not be the case after https://github.com/kensnyder/quill-image-resize-module/pull/3 is merged.  Time permitting, I'll see if I can verify that this is the case, though.

**Comment by kensnyder** [comment]
PR #3 uses Webpack instead.
