### ISSUE TITLE
Append control divs to Quill's parent element instead of document body?

### ISSUE THREAD

**Issue by goldpbear** [kensnyder/quill-image-resize-module#5]
Thanks for putting this module together--we were badly in need of a way to resize images in Quill and this really helped us out!

We have a single-page application with a Quill editor inside a scrollable container. Since the control boxes of the image resize module are appended to `document.body`, I found that scrolling the container would cause the resize boxes to drift away from their image:

<img width="393" alt="screen shot 2017-04-06 at 11 32 41 am" src="https://cloud.githubusercontent.com/assets/9222338/24769941/1f0283ea-1abd-11e7-8dbe-517002ed8cd6.png">

To fix this, instead of appending the control divs to `document.body`, I append them to `quill.root.parentElement`. And instead of calculating their position using `this.img.getBoundingClientRect()`, I use `this.img.offsetLeft` and `this.img.offsetTop` to get positions relative to the container.

I'm not sure how generalizable this is, though. Would there be any drawbacks to always appending the control divs to `quill.root.parentElement`?

In any case, thanks a lot for your work on this module.

**Comment by kensnyder** [comment]
It is hard to predict what conflicts there might be with `quill.root.parentElement`. I'd rather add a scroll listener to the root, keep the handles on the body and move them on scroll. I'll work on a patch.

**Comment by goldpbear** [comment]
Fair enough. Thanks for looking into it!
