### ISSUE TITLE
Resize border box overflow the editor

### ISSUE THREAD

**Issue by ycjcl868** [kensnyder/quill-image-resize-module#55]
## ScreenShot
![image](https://user-images.githubusercontent.com/13595509/45370563-19eaf180-b61b-11e8-9d2c-3fdd3f719c27.png)

![image](https://user-images.githubusercontent.com/13595509/46056021-4e18f300-c181-11e8-9b32-eb39b6d89284.png)

**Comment by LoremipsumSharp** [comment]
> 
> ## ScreenShot
> 
> ![image](https://user-images.githubusercontent.com/13595509/45370563-19eaf180-b61b-11e8-9d2c-3fdd3f719c27.png)
> 
> ![image](https://user-images.githubusercontent.com/13595509/46056021-4e18f300-c181-11e8-9b32-eb39b6d89284.png)

You can try to add the "overflow:auto"  to the editor container

**Comment by ycjcl868** [comment]
@morining but the pic can't be fit for the dashed box.


![image](https://user-images.githubusercontent.com/13595509/46117328-38fc9c80-c233-11e8-9025-f5b6a726593f.png)

**Comment by LoremipsumSharp** [comment]
> @morining but the pic can't be fit for the dashed box.
> 
> ![image](https://user-images.githubusercontent.com/13595509/46117328-38fc9c80-c233-11e8-9025-f5b6a726593f.png)
I am using the following class to style the editor.If you don`t have a flex editor,you should use "max-height : xxx" and overflow : auto to style the editor simultaneously 
```
        .flex-editor {
            flex: 1;
            display: flex;
            flex-flow: column nowrap;
            overflow: auto;
        }
```

**Comment by ycjcl868** [comment]
@morining it don't work.

![image](https://user-images.githubusercontent.com/13595509/46144183-c4efe200-c28e-11e8-9b52-8c87e64a005a.png)

**Comment by LoremipsumSharp** [comment]
Take a look at the Demo in the repo .The code snippet from demo using the max-height and overflow to style the editor.
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quill Image Resize Module Demo</title>
    <script src="//cdn.quilljs.com/1.2.2/quill.min.js"></script>
    <link href="//cdn.quilljs.com/1.2.2/quill.snow.css" rel="stylesheet">
    <script src="../image-resize.min.js"></script>
</head>

<body>
<h1>Quill Image Resize Module Demo</h1>
<div id="editor" style="max-height:500px;overflow:auto">
    <p>Click on the Image Below to resize</p>
    <p><img src="http://ri-sandbox.s3.amazonaws.com/qulljs.png"></p>
    <p>Some initial <strong>bold</strong> text</p>
    <p><img src="http://ri-sandbox.s3.amazonaws.com/pi-rate.png"></p>
</div>
<p>Also see <a href="https://github.com/kensnyder/quill-image-drop-module">quill-image-drop-module</a>,
    a module that enables copy-paste and drag/drop for Quill.</p>
<script src="script.js"></script>
</body>

</html>
```

**Comment by ycjcl868** [comment]
thx, I fixed.

![image](https://user-images.githubusercontent.com/13595509/46997731-07e8fb00-d153-11e8-8c88-d6746140f38b.png)

**Comment by invincibleyolk** [comment]
> thx, I fixed.
> 
> ![image](https://user-images.githubusercontent.com/13595509/46997731-07e8fb00-d153-11e8-8c88-d6746140f38b.png)

Thanks mate, that helps a lot!
