### ISSUE TITLE
when I scroll editor content, the position of overlay will be inaccurated.

### ISSUE THREAD

**Issue by chentianming11** [kensnyder/quill-image-resize-module#63]
when I scroll editor content, the position of overlay will be inaccurated.
![error](https://user-images.githubusercontent.com/30620547/48058039-710edc00-e1f0-11e8-93b1-949ad0dae9d4.jpg)

**Comment by samraghul** [comment]
same issue i'm having

**Comment by EnochGao** [comment]
请问你是如何import imageresize from quill-image-resize-module模块的，我用的是angular4,会有报错

**Comment by chentianming11** [comment]
> 请问你是如何从quill-image-resize-module模块的导入imageresize，我用的是angular4，会有报错

我用的是vue2，导入的直接如下：
import  ImageResize  from 'quill-image-resize-module';
注意，不需要大括号解构。我按文档加解构也会有问题。
如果还是报错，就是改下webpack的配置适配下。这个其他issue里面有提到

**Comment by lyuehh** [comment]
Add `this.quill.root.addEventListener('scroll', this.hide, false);` under `this.quill.root.addEventListener('click', this.handleClick, false)` fix this

or use my fork `quill-image-resize-module-withfix@3.0.5`

**Comment by chentianming11** [comment]
> Add `this.quill.root.addEventListener('scroll', this.hide, false);` under `this.quill.root.addEventListener('click', this.handleClick, false)` fix this
> 
> or use my fork `quill-image-resize-module-withfix@3.0.5`

ok, thanks
