### ISSUE TITLE
cannot import ImageResize from 'quill-image-resize-module';

### ISSUE THREAD

**Issue by EnochGao** [kensnyder/quill-image-resize-module#65]
hello，I am using anular4, when I put the mouse over it, the prompt
`
Could not find the declaration file "C:./Users/Ying/Desktop/work/node_modules/_quill-image-resize-module@3.0.0@quill-image-resize-module/ image" of the module "Sleeve Image Resizing Module" -resize.min.js "implicitly possesses" any "type."
If it does, try `npm install @ types / quill-image-resize-module` or add a new declaration (.d.ts) file containing `declare module'quill-image-resize-module';`[7016]`

**Comment by EonchGao** [comment]
How should I solve it?

**Comment by jagotronic** [comment]
I have the same problem importing module

**Comment by EnochGao** [comment]
i solved it,it need you add "noImplicitAny": false in your tsconfig.json @jagotronic

**Comment by benwinding** [comment]
This format worked for me...

``` js
import ImageResize from 'quill-image-resize-module';
```

**Comment by myoneflag** [comment]
I am using React, have no tsconfig.json. How to solve it? please

**Comment by fonzane** [comment]
> i solved it,it need you add "noImplicitAny": false in your tsconfig.json @jagotronic

This didn't work for me. Does anyone have a solution on how to import ImageResize?

**Comment by EnochGao** [comment]
> > i solved it,it need you add "noImplicitAny": false in your tsconfig.json @jagotronic
> 
> This didn't work for me. Does anyone have a solution on how to import ImageResize?

You can create a type.d.ts file:
```ts
declare module 'quill-image-resize-module';
```
