### ISSUE TITLE
Resize cannot work in mobile phone

### ISSUE THREAD

**Issue by hanerx** [kensnyder/quill-image-resize-module#70]
I tried to use this plugin in mobile phone, but the resize button cannot work and console did not have any info or warning.

**Comment by ggjersund** [comment]
Also hoping for a quick fix for this.
I suppose some edit of `src/modules/Resize.js` would make it work.

**Comment by ashish0910** [comment]
@ggjersund , @hanerx Checkout my forked [here](https://github.com/ashish0910/quill-image-resize-module) . I have also opened a pull request for it #79 .

**Comment by iamflowerdog** [comment]
> @ggjersund , @hanerx Checkout my forked [here](https://github.com/ashish0910/quill-image-resize-module) . I have also opened a pull request for it #79 .

thanks for you forked, use you code that have reslove my problem.

**Comment by hanerx** [comment]
> @ggjersund , @hanerx Checkout my forked [here](https://github.com/ashish0910/quill-image-resize-module) . I have also opened a pull request for it #79 .

thanks, that works!
