### ISSUE TITLE
console.log statement in constructor

### ISSUE THREAD

**Issue by lozjackson** [kensnyder/quill-image-resize-module#8]
Thanks for this module.. works well..

Can you remove the `console.log` statement on [this line](https://github.com/kensnyder/quill-image-resize-module/blob/master/src/ImageResize.js#L45)?

**Comment by lozjackson** [comment]
any chance of publishing a patch release so that I can use this package from npm without the console.log statement..

**Comment by Waseem826** [comment]
waiting for latest npm release with this console.log removed

**Comment by mzaidkhan** [comment]
Urgently, Need the minified version without the console.log
Thanks for helping in advance.
