### ISSUE TITLE
插件无法引入

### ISSUE THREAD

**Issue by cangyu1993** [kensnyder/quill-image-resize-module#83]
无法引入
```
import {quillEditor, Quill} from 'vue-quill-editor'
  import {container, ImageExtend, QuillWatch} from 'quill-image-extend-module'
  // import ImageResize  from 'quill-image-resize-module'

  Quill.register('modules/ImageExtend', ImageExtend)
  // Quill.register('modules/imageResize', ImageResize)
```
![image](https://user-images.githubusercontent.com/42930030/64932907-aeaead80-d874-11e9-972f-28e4cd206079.png)

**Comment by meiqinLiu** [comment]
请问这个问题解决了吗

**Comment by cangyu1993** [comment]
图片大小改变插件吗？可以解决了，我也忘记怎么搞的了，加个联系发你吧

**Comment by YogaLin** [comment]
Try adding quill to webpack plugin:

`
plugins: [
    new webpack.ProvidePlugin({
      'window.Quill': 'quill'
    })
  ]
`

**Comment by cangyu1993** [comment]
正如楼上所设置，开发模式和生产模式下都加上就行了
这是 我的（开发模式下），生产模式也配好最好
![image](https://user-images.githubusercontent.com/42930030/68105322-11d5cb80-ff19-11e9-897f-9f7c6e6d0944.png)
