### ISSUE TITLE
React image size inside quill editor does not represent actual size

### ISSUE THREAD

**Issue by NirajVyas** [kensnyder/quill-image-resize-module#89]
I am having trouble displaying the new sized image inside the quill editor once I have resized it. On refresh it goes back to its original size. This is my setup:

`import ReactQuill, { Quill } from 'react-quill';
Quill.register('modules/imageResize', ImageResize);
Quill.register('modules/imageDrop', ImageDrop);

  public render() {
    const { value, theme, readOnly } = this.state;

    const modules = {
      clipboard: QuillConstants.clipboard,
      imageDrop: true,
      imageResize: {
        displaySize: true,
        handleStyles: {
          backgroundColor: 'black',
          border: 'none',
          color: 'white',
        },
        modules: ['Resize', 'DisplaySize', 'Toolbar'],
      },
      toolbar: {
        container: QuillConstants.toolbar(DIRECTIONS.LTR),
        handlers: { image: this.imageHandler },
      },
    };

    return (
      <div className="quill">
        <ReactQuill
          id={'rest'}
          ref={(el: any) => this.reactQuillRef = el}
          theme={theme}
          onChange={this.onEditorChange}
          value={value}
          modules={modules}
          formats={QuillConstants.formats}
          bounds={'.quill'}
          placeholder={this.placeholder()}
          readOnly={readOnly}
        />
      </div>
    );
  }
`

If I inspect the image inside the quill editor using the react chrome extension I do see the width attribute being passed via props:

<img width="386" alt="new" src="https://user-images.githubusercontent.com/6872955/67414474-131f0400-f5bb-11e9-89bf-e062d7642c7b.png">

However inside `state` the attributes property does not exist:

<img width="401" alt="Screen Shot 2019-10-23 at 17 28 47" src="https://user-images.githubusercontent.com/6872955/67414333-c89d8780-f5ba-11e9-8c49-15f8d1e2d653.png">

Is there something wrong with my setup or is this a known issue?

Thanks

**Comment by bcspragu** [comment]
I noticed this is closed, did you figure this out? I'm noticing the same thing - width is recorded, but only respected in `readOnly` mode.
